version: '1'

services:
  database:
    image: mongo
    container_name: mydatabase
    command: --auth
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - ./data:/data/db
    expose:
      - "27017"

  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://root:example@mydatabase:27017/
    depends_on:
      - database


  db-exporter:
    image: bitnami/mongodb-exporter:latest
    environment:
      - MONGODB_URI=mongodb://root:example@mydatabase:27017/
    depends_on:
      - database

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    ports:
      - 9090:9090
    depends_on:
      - db-exporter
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml

  grafana:
    build: ./grafana
    ports:
      - 3000:3000
  
volumes:
  prometheus-data: